services:
  postgres:
    image: postgres:latest
    container_name: petroflow_postgres
    environment:
      POSTGRES_DB: petroflow
      POSTGRES_USER: petroflow_user
      POSTGRES_PASSWORD: PetroFlow1
    ports:
      - "5432:5432"  # Keep this port as it works fine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - petroflow_network

  adminer:
    image: adminer:latest
    container_name: petroflow_adminer
    ports:
      - "8082:8080"  # Changed to 8082 to avoid conflicts
    networks:
      - petroflow_network

volumes:
  postgres_data:

networks:
  petroflow_network:
