#!/usr/bin/env bash
set -euo pipefail

BASE_DIR="src/main/java/com/angerasilas/petroflow_backend"

if [[ ! -d "src/main/java" ]]; then
  echo "Error: run this from the Spring Boot project root (where src/main/java exists)."
  exit 1
fi

mkdir -p "$BASE_DIR"

FILES=$(cat <<'EOF'
PetroflowBackendApplication.java
common/api/ApiResponse.java
common/api/PagedResponse.java
common/api/BulkOperationResponse.java
common/api/PageRequestDto.java
common/api/SortRequestDto.java
common/api/ApiMetadata.java
common/exception/ErrorResponse.java
common/exception/GlobalExceptionHandler.java
common/exception/ResourceNotFoundException.java
common/exception/BadRequestException.java
common/exception/UnauthorizedException.java
common/exception/ForbiddenException.java
common/exception/ConflictException.java
common/exception/ValidationException.java
common/exception/BusinessRuleViolationException.java
common/exception/TenantResolutionException.java
common/exception/SchemaProvisioningException.java
common/exception/SyncConflictException.java
common/response/SuccessResponse.java
common/response/ErrorDetail.java
common/response/ValidationErrorResponse.java
common/response/FieldValidationError.java
common/validation/ValidPhoneNumber.java
common/validation/ValidKraPin.java
common/validation/ValidTenantCode.java
common/validation/ValidFuelVolume.java
common/validation/ValidMoney.java
common/validation/ValidDateRange.java
common/validation/PhoneNumberValidator.java
common/validation/KraPinValidator.java
common/validation/TenantCodeValidator.java
common/validation/DateRangeValidator.java
common/enums/RecordStatus.java
common/enums/ActiveStatus.java
common/enums/ApprovalStatus.java
common/enums/RequestStatus.java
common/enums/IncidentStatus.java
common/enums/ShiftStatus.java
common/enums/SaleStatus.java
common/enums/PaymentStatus.java
common/enums/StockMovementType.java
common/enums/TenantStatus.java
common/enums/SubscriptionStatus.java
common/enums/NotificationChannelType.java
common/enums/FacilityType.java
common/enums/ProductType.java
common/enums/FuelType.java
common/enums/EmploymentStatus.java
common/util/DateTimeUtils.java
common/util/MoneyUtils.java
common/util/StringUtils.java
common/util/JsonUtils.java
common/util/SlugUtils.java
common/util/PhoneUtils.java
common/util/SecurityUtils.java
common/util/TenantUtils.java
common/util/IdGenerator.java
common/constants/ApiPaths.java
common/constants/SecurityConstants.java
common/constants/TenantConstants.java
common/constants/CacheNames.java
common/constants/HeaderNames.java
common/constants/ClaimNames.java
common/constants/SystemDefaults.java
common/mapper/CentralMapperConfig.java
common/mapper/MappingUtils.java
common/mapper/CycleAvoidingMappingContext.java
config/JacksonConfig.java
config/SecurityConfig.java
config/PasswordEncoderConfig.java
config/RedisConfig.java
config/CacheConfig.java
config/AsyncConfig.java
config/SchedulingConfig.java
config/ObservabilityConfig.java
config/OpenApiConfig.java
config/CorsConfig.java
config/WebMvcConfig.java
config/RateLimitConfig.java
config/JpaAuditingConfig.java
config/FlywayConfig.java
config/ObjectMapperConfig.java
infrastructure/persistence/BaseEntity.java
infrastructure/persistence/AuditableEntity.java
infrastructure/persistence/SoftDeletableEntity.java
infrastructure/persistence/BaseRepository.java
infrastructure/persistence/TenantAwareRepository.java
infrastructure/persistence/JpaSpecificationBuilder.java
infrastructure/persistence/QuerydslConfig.java
infrastructure/persistence/converters/JsonNodeConverter.java
infrastructure/persistence/converters/LocalDateTimeConverter.java
infrastructure/persistence/converters/MoneyConverter.java
infrastructure/cache/CacheService.java
infrastructure/cache/RedisCacheService.java
infrastructure/cache/CacheKeyBuilder.java
infrastructure/cache/TenantCacheKeyBuilder.java
infrastructure/messaging/DomainEventPublisher.java
infrastructure/messaging/DomainEventHandler.java
infrastructure/messaging/EmailEventPublisher.java
infrastructure/messaging/NotificationEventPublisher.java
infrastructure/messaging/AuditEventPublisher.java
infrastructure/scheduling/JobExecutionLog.java
infrastructure/scheduling/JobExecutionLogRepository.java
infrastructure/scheduling/JobExecutionService.java
infrastructure/scheduling/JobLockService.java
infrastructure/observability/TraceLoggingService.java
infrastructure/observability/RequestCorrelationFilter.java
infrastructure/observability/MetricsService.java
infrastructure/observability/TenantMetricsTagsProvider.java
infrastructure/storage/FileStorageService.java
infrastructure/storage/LocalFileStorageService.java
infrastructure/storage/AttachmentMetadata.java
infrastructure/storage/AttachmentMetadataRepository.java
infrastructure/storage/FileDownloadService.java
infrastructure/external/email/EmailClient.java
infrastructure/external/email/SmtpEmailClient.java
infrastructure/external/email/EmailRequest.java
infrastructure/external/email/EmailResponse.java
infrastructure/external/sms/SmsClient.java
infrastructure/external/sms/SmsRequest.java
infrastructure/external/sms/SmsResponse.java
infrastructure/external/payment/PaymentGatewayClient.java
infrastructure/external/payment/MpesaClient.java
infrastructure/external/payment/PaymentGatewayRequest.java
infrastructure/external/payment/PaymentGatewayResponse.java
security/auth/controller/AuthController.java
security/auth/dto/LoginRequest.java
security/auth/dto/LoginResponse.java
security/auth/dto/RefreshTokenRequest.java
security/auth/dto/RefreshTokenResponse.java
security/auth/dto/ForgotPasswordRequest.java
security/auth/dto/ResetPasswordRequest.java
security/auth/dto/ChangePasswordRequest.java
security/auth/dto/CurrentSessionResponse.java
security/auth/service/AuthService.java
security/auth/service/PasswordResetService.java
security/auth/service/RefreshTokenService.java
security/auth/service/impl/AuthServiceImpl.java
security/auth/service/impl/PasswordResetServiceImpl.java
security/auth/service/impl/RefreshTokenServiceImpl.java
security/auth/entity/RefreshToken.java
security/jwt/JwtUtil.java
security/jwt/JwtTokenProvider.java
security/jwt/JwtClaimsFactory.java
security/jwt/JwtAuthenticationFilter.java
security/jwt/JwtAuthenticationEntryPoint.java
security/jwt/JwtAccessDeniedHandler.java
security/jwt/JwtTokenBlacklistService.java
security/rbac/controller/RoleController.java
security/rbac/controller/PermissionController.java
security/rbac/dto/RoleRequest.java
security/rbac/dto/RoleResponse.java
security/rbac/dto/PermissionRequest.java
security/rbac/dto/PermissionResponse.java
security/rbac/dto/RolePermissionsResponse.java
security/rbac/entity/Role.java
security/rbac/entity/Permission.java
security/rbac/entity/RolePermission.java
security/rbac/repository/RoleRepository.java
security/rbac/repository/PermissionRepository.java
security/rbac/repository/RolePermissionRepository.java
security/rbac/service/RoleService.java
security/rbac/service/PermissionService.java
security/rbac/service/RbacAuthorizationService.java
security/rbac/service/impl/RoleServiceImpl.java
security/rbac/service/impl/PermissionServiceImpl.java
security/rbac/service/impl/RbacAuthorizationServiceImpl.java
security/rbac/mapper/RoleMapper.java
security/rbac/mapper/PermissionMapper.java
security/session/dto/DeviceInfo.java
security/session/dto/DeviceSessionResponse.java
security/session/dto/RevokeSessionRequest.java
security/session/entity/DeviceSession.java
security/session/repository/DeviceSessionRepository.java
security/session/service/DeviceSessionService.java
security/session/service/impl/DeviceSessionServiceImpl.java
security/session/controller/SessionController.java
security/audit/entity/AuditLog.java
security/audit/repository/AuditLogRepository.java
security/audit/service/AuditLogService.java
security/audit/service/impl/AuditLogServiceImpl.java
security/audit/dto/AuditLogResponse.java
security/audit/controller/AuditLogController.java
tenancy/context/TenantContext.java
tenancy/context/TenantContextHolder.java
tenancy/context/TenantContextValidator.java
tenancy/context/TenantExecutionContext.java
tenancy/resolution/TenantResolutionService.java
tenancy/resolution/JwtTenantResolver.java
tenancy/resolution/HeaderTenantResolver.java
tenancy/resolution/SubdomainTenantResolver.java
tenancy/resolution/CompositeTenantResolver.java
tenancy/resolution/TenantIdentifierResolver.java
tenancy/schema/SchemaService.java
tenancy/schema/TenantSchemaProvisioningService.java
tenancy/schema/TenantSchemaNamingStrategy.java
tenancy/schema/TenantSchemaDropService.java
tenancy/schema/impl/SchemaServiceImpl.java
tenancy/schema/impl/TenantSchemaProvisioningServiceImpl.java
tenancy/schema/impl/TenantSchemaDropServiceImpl.java
tenancy/migration/GlobalSchemaMigrationService.java
tenancy/migration/TenantMigrationService.java
tenancy/migration/FlywayMultiTenantMigrator.java
tenancy/migration/BaselineTenantMigrationRunner.java
tenancy/migration/impl/GlobalSchemaMigrationServiceImpl.java
tenancy/migration/impl/TenantMigrationServiceImpl.java
tenancy/bootstrap/DataInitializer.java
tenancy/bootstrap/TenantBootstrapService.java
tenancy/bootstrap/TenantAdminBootstrapper.java
tenancy/bootstrap/DefaultRoleSeeder.java
tenancy/bootstrap/DefaultPermissionSeeder.java
tenancy/bootstrap/DefaultFeatureFlagSeeder.java
tenancy/bootstrap/DefaultPlanSeeder.java
tenancy/lifecycle/TenantOnboardingService.java
tenancy/lifecycle/TenantActivationService.java
tenancy/lifecycle/TenantSuspensionService.java
tenancy/lifecycle/TenantDeletionService.java
tenancy/lifecycle/impl/TenantOnboardingServiceImpl.java
tenancy/lifecycle/impl/TenantActivationServiceImpl.java
tenancy/lifecycle/impl/TenantSuspensionServiceImpl.java
tenancy/lifecycle/impl/TenantDeletionServiceImpl.java
tenancy/web/TenantContextFilter.java
tenancy/web/TenantRequestInterceptor.java
tenancy/web/TenantWebConfig.java
platform/user/controller/UserController.java
platform/user/controller/UserProfileController.java
platform/user/dto/UserRequest.java
platform/user/dto/UserResponse.java
platform/user/dto/UserProfileResponse.java
platform/user/dto/UserSummaryResponse.java
platform/user/dto/UpdateUserStatusRequest.java
platform/user/entity/User.java
platform/user/entity/UserProfile.java
platform/user/entity/UserTenantMembership.java
platform/user/entity/UserPasswordHistory.java
platform/user/repository/UserRepository.java
platform/user/repository/UserProfileRepository.java
platform/user/repository/UserTenantMembershipRepository.java
platform/user/repository/UserPasswordHistoryRepository.java
platform/user/service/UserService.java
platform/user/service/UserProfileService.java
platform/user/service/impl/UserServiceImpl.java
platform/user/service/impl/UserProfileServiceImpl.java
platform/user/mapper/UserMapper.java
platform/user/mapper/UserProfileMapper.java
platform/organization/controller/OrganizationController.java
platform/organization/controller/OrganizationOwnerController.java
platform/organization/controller/BranchController.java
platform/organization/controller/OrganizationSettingsController.java
platform/organization/dto/OrganizationRequest.java
platform/organization/dto/OrganizationResponse.java
platform/organization/dto/OrganizationOwnerRequest.java
platform/organization/dto/OrganizationOwnerResponse.java
platform/organization/dto/BranchRequest.java
platform/organization/dto/BranchResponse.java
platform/organization/dto/OrganizationSettingsResponse.java
platform/organization/entity/Organization.java
platform/organization/entity/OrganizationOwner.java
platform/organization/entity/Branch.java
platform/organization/entity/OrganizationSettings.java
platform/organization/entity/OrganizationFacilityLink.java
platform/organization/entity/OrganizationBrandLink.java
platform/organization/repository/OrganizationRepository.java
platform/organization/repository/OrganizationOwnerRepository.java
platform/organization/repository/BranchRepository.java
platform/organization/repository/OrganizationSettingsRepository.java
platform/organization/repository/OrganizationBrandLinkRepository.java
platform/organization/service/OrganizationService.java
platform/organization/service/OrganizationOwnerService.java
platform/organization/service/BranchService.java
platform/organization/service/impl/OrganizationServiceImpl.java
platform/organization/service/impl/OrganizationOwnerServiceImpl.java
platform/organization/service/impl/BranchServiceImpl.java
platform/organization/mapper/OrganizationMapper.java
platform/organization/mapper/OrganizationOwnerMapper.java
platform/organization/mapper/BranchMapper.java
platform/subscription/controller/SubscriptionController.java
platform/subscription/controller/SubscriptionPlanController.java
platform/subscription/dto/SubscriptionRequest.java
platform/subscription/dto/SubscriptionResponse.java
platform/subscription/dto/SubscriptionPlanRequest.java
platform/subscription/dto/SubscriptionPlanResponse.java
platform/subscription/entity/Subscription.java
platform/subscription/entity/SubscriptionPlan.java
platform/subscription/entity/PlanFeature.java
platform/subscription/entity/TenantSubscriptionHistory.java
platform/subscription/repository/SubscriptionRepository.java
platform/subscription/repository/SubscriptionPlanRepository.java
platform/subscription/repository/PlanFeatureRepository.java
platform/subscription/repository/TenantSubscriptionHistoryRepository.java
platform/subscription/service/SubscriptionService.java
platform/subscription/service/SubscriptionPlanService.java
platform/subscription/service/impl/SubscriptionServiceImpl.java
platform/subscription/service/impl/SubscriptionPlanServiceImpl.java
platform/subscription/mapper/SubscriptionMapper.java
platform/subscription/mapper/SubscriptionPlanMapper.java
platform/brand/controller/BrandController.java
platform/brand/dto/BrandRequest.java
platform/brand/dto/BrandResponse.java
platform/brand/entity/Brand.java
platform/brand/entity/BrandPolicy.java
platform/brand/entity/BrandDealerAgreement.java
platform/brand/repository/BrandRepository.java
platform/brand/repository/BrandPolicyRepository.java
platform/brand/repository/BrandDealerAgreementRepository.java
platform/brand/service/BrandService.java
platform/brand/service/impl/BrandServiceImpl.java
platform/brand/mapper/BrandMapper.java
platform/featureflag/controller/FeatureFlagController.java
platform/featureflag/dto/FeatureFlagRequest.java
platform/featureflag/dto/FeatureFlagResponse.java
platform/featureflag/dto/TenantFeatureFlagResponse.java
platform/featureflag/entity/FeatureFlag.java
platform/featureflag/entity/TenantFeatureFlag.java
platform/featureflag/repository/FeatureFlagRepository.java
platform/featureflag/repository/TenantFeatureFlagRepository.java
platform/featureflag/service/FeatureFlagService.java
platform/featureflag/service/impl/FeatureFlagServiceImpl.java
platform/featureflag/mapper/FeatureFlagMapper.java
platform/billing/controller/BillingAccountController.java
platform/billing/controller/BillingInvoiceController.java
platform/billing/controller/BillingPaymentController.java
platform/billing/dto/BillingAccountResponse.java
platform/billing/dto/BillingInvoiceResponse.java
platform/billing/dto/BillingPaymentResponse.java
platform/billing/dto/RecordBillingPaymentRequest.java
platform/billing/entity/BillingAccount.java
platform/billing/entity/BillingInvoice.java
platform/billing/entity/BillingPayment.java
platform/billing/repository/BillingAccountRepository.java
platform/billing/repository/BillingInvoiceRepository.java
platform/billing/repository/BillingPaymentRepository.java
platform/billing/service/BillingService.java
platform/billing/service/impl/BillingServiceImpl.java
platform/billing/mapper/BillingMapper.java
platform/notification/controller/GlobalNotificationController.java
platform/notification/controller/NotificationTemplateController.java
platform/notification/dto/NotificationTemplateRequest.java
platform/notification/dto/NotificationTemplateResponse.java
platform/notification/dto/GlobalNotificationResponse.java
platform/notification/entity/GlobalNotification.java
platform/notification/entity/NotificationTemplate.java
platform/notification/entity/NotificationChannel.java
platform/notification/repository/GlobalNotificationRepository.java
platform/notification/repository/NotificationTemplateRepository.java
platform/notification/repository/NotificationChannelRepository.java
platform/notification/service/GlobalNotificationService.java
platform/notification/service/NotificationTemplateService.java
platform/notification/service/impl/GlobalNotificationServiceImpl.java
platform/notification/service/impl/NotificationTemplateServiceImpl.java
platform/notification/mapper/NotificationTemplateMapper.java
modules/sales/controller/SalesController.java
modules/sales/controller/RefundController.java
modules/sales/controller/CreditSaleController.java
modules/sales/dto/request/CreateSaleRequest.java
modules/sales/dto/request/UpdateSaleRequest.java
modules/sales/dto/request/RecordSalePaymentRequest.java
modules/sales/dto/request/RefundSaleRequest.java
modules/sales/dto/request/CreateCreditSaleRequest.java
modules/sales/dto/response/SaleResponse.java
modules/sales/dto/response/SaleLineItemResponse.java
modules/sales/dto/response/SalePaymentResponse.java
modules/sales/dto/response/RefundResponse.java
modules/sales/dto/response/CreditSaleResponse.java
modules/sales/dto/summary/SalesSummaryResponse.java
modules/sales/dto/summary/DailySalesSummaryResponse.java
modules/sales/entity/Sale.java
modules/sales/entity/SaleLineItem.java
modules/sales/entity/SalePayment.java
modules/sales/entity/Refund.java
modules/sales/entity/CreditSale.java
modules/sales/entity/DailySalesSummary.java
modules/sales/repository/SaleRepository.java
modules/sales/repository/SaleLineItemRepository.java
modules/sales/repository/SalePaymentRepository.java
modules/sales/repository/RefundRepository.java
modules/sales/repository/CreditSaleRepository.java
modules/sales/repository/DailySalesSummaryRepository.java
modules/sales/service/SalesService.java
modules/sales/service/RefundService.java
modules/sales/service/CreditSaleService.java
modules/sales/service/SalesAnalyticsService.java
modules/sales/service/impl/SalesServiceImpl.java
modules/sales/service/impl/RefundServiceImpl.java
modules/sales/service/impl/CreditSaleServiceImpl.java
modules/sales/service/impl/SalesAnalyticsServiceImpl.java
modules/sales/mapper/SaleMapper.java
modules/sales/mapper/SaleLineItemMapper.java
modules/sales/mapper/RefundMapper.java
modules/sales/validation/SaleValidator.java
modules/inventory/controller/StockController.java
modules/inventory/controller/InventoryAdjustmentController.java
modules/inventory/controller/StockMovementController.java
modules/inventory/controller/SupplierController.java
modules/inventory/dto/request/CreateStockItemRequest.java
modules/inventory/dto/request/CreateStockMovementRequest.java
modules/inventory/dto/request/CreateInventoryAdjustmentRequest.java
modules/inventory/dto/request/CreateSupplierRequest.java
modules/inventory/dto/response/StockItemResponse.java
modules/inventory/dto/response/StockMovementResponse.java
modules/inventory/dto/response/InventoryAdjustmentResponse.java
modules/inventory/dto/response/SupplierResponse.java
modules/inventory/dto/summary/StockSummaryResponse.java
modules/inventory/entity/StockItem.java
modules/inventory/entity/StockMovement.java
modules/inventory/entity/InventoryAdjustment.java
modules/inventory/entity/Supplier.java
modules/inventory/entity/GoodsReceipt.java
modules/inventory/entity/TransferOrder.java
modules/inventory/repository/StockItemRepository.java
modules/inventory/repository/StockMovementRepository.java
modules/inventory/repository/InventoryAdjustmentRepository.java
modules/inventory/repository/SupplierRepository.java
modules/inventory/repository/GoodsReceiptRepository.java
modules/inventory/repository/TransferOrderRepository.java
modules/inventory/service/StockService.java
modules/inventory/service/InventoryAdjustmentService.java
modules/inventory/service/SupplierService.java
modules/inventory/service/impl/StockServiceImpl.java
modules/inventory/service/impl/InventoryAdjustmentServiceImpl.java
modules/inventory/service/impl/SupplierServiceImpl.java
modules/inventory/mapper/StockItemMapper.java
modules/inventory/mapper/StockMovementMapper.java
modules/inventory/mapper/InventoryAdjustmentMapper.java
modules/inventory/validation/InventoryValidator.java
modules/product/controller/ProductController.java
modules/product/controller/ProductCategoryController.java
modules/product/dto/request/CreateProductRequest.java
modules/product/dto/request/UpdateProductRequest.java
modules/product/dto/request/CreateProductCategoryRequest.java
modules/product/dto/response/ProductResponse.java
modules/product/dto/response/ProductCategoryResponse.java
modules/product/dto/response/ProductPriceResponse.java
modules/product/dto/summary/ProductSummaryResponse.java
modules/product/entity/Product.java
modules/product/entity/ProductCategory.java
modules/product/entity/ProductPrice.java
modules/product/entity/ProductUnit.java
modules/product/entity/ProductBarcode.java
modules/product/repository/ProductRepository.java
modules/product/repository/ProductCategoryRepository.java
modules/product/repository/ProductPriceRepository.java
modules/product/repository/ProductBarcodeRepository.java
modules/product/service/ProductService.java
modules/product/service/ProductCategoryService.java
modules/product/service/impl/ProductServiceImpl.java
modules/product/service/impl/ProductCategoryServiceImpl.java
modules/product/mapper/ProductMapper.java
modules/product/validation/ProductValidator.java
modules/fuel/controller/FuelProductController.java
modules/fuel/controller/FuelPricingController.java
modules/fuel/controller/PumpController.java
modules/fuel/controller/PumpMeterReadingController.java
modules/fuel/controller/TankStorageController.java
modules/fuel/controller/NozzleController.java
modules/fuel/controller/WetStockController.java
modules/fuel/dto/request/CreateFuelProductRequest.java
modules/fuel/dto/request/CreateFuelPricingRequest.java
modules/fuel/dto/request/CreatePumpRequest.java
modules/fuel/dto/request/RecordPumpMeterReadingRequest.java
modules/fuel/dto/request/CreateTankStorageRequest.java
modules/fuel/dto/request/RecordTankDipRequest.java
modules/fuel/dto/response/FuelProductResponse.java
modules/fuel/dto/response/FuelPricingResponse.java
modules/fuel/dto/response/PumpResponse.java
modules/fuel/dto/response/PumpMeterReadingResponse.java
modules/fuel/dto/response/TankStorageResponse.java
modules/fuel/dto/response/NozzleResponse.java
modules/fuel/dto/response/WetStockVarianceResponse.java
modules/fuel/dto/summary/FuelStockSummaryResponse.java
modules/fuel/entity/FuelProduct.java
modules/fuel/entity/FuelPricing.java
modules/fuel/entity/Pump.java
modules/fuel/entity/Nozzle.java
modules/fuel/entity/PumpMeterReading.java
modules/fuel/entity/TankStorage.java
modules/fuel/entity/TankDipReading.java
modules/fuel/entity/WetStockVariance.java
modules/fuel/entity/FuelDelivery.java
modules/fuel/repository/FuelProductRepository.java
modules/fuel/repository/FuelPricingRepository.java
modules/fuel/repository/PumpRepository.java
modules/fuel/repository/NozzleRepository.java
modules/fuel/repository/PumpMeterReadingRepository.java
modules/fuel/repository/TankStorageRepository.java
modules/fuel/repository/TankDipReadingRepository.java
modules/fuel/repository/WetStockVarianceRepository.java
modules/fuel/service/FuelProductService.java
modules/fuel/service/FuelPricingService.java
modules/fuel/service/PumpService.java
modules/fuel/service/WetStockService.java
modules/fuel/service/impl/FuelProductServiceImpl.java
modules/fuel/service/impl/FuelPricingServiceImpl.java
modules/fuel/service/impl/PumpServiceImpl.java
modules/fuel/service/impl/WetStockServiceImpl.java
modules/fuel/mapper/FuelProductMapper.java
modules/fuel/mapper/FuelPricingMapper.java
modules/fuel/mapper/PumpMapper.java
modules/fuel/mapper/PumpMeterReadingMapper.java
modules/fuel/mapper/TankStorageMapper.java
modules/fuel/validation/FuelValidator.java
modules/shift/controller/ShiftController.java
modules/shift/controller/ShiftHandoverController.java
modules/shift/controller/ShiftScheduleController.java
modules/shift/dto/request/CreateShiftRequest.java
modules/shift/dto/request/CreateShiftHandoverRequest.java
modules/shift/dto/request/CreateShiftScheduleRequest.java
modules/shift/dto/response/ShiftResponse.java
modules/shift/dto/response/ShiftHandoverResponse.java
modules/shift/dto/response/ShiftScheduleResponse.java
modules/shift/dto/summary/ShiftSummaryResponse.java
modules/shift/entity/Shift.java
modules/shift/entity/ShiftHandover.java
modules/shift/entity/ShiftSchedule.java
modules/shift/entity/ShiftCashUp.java
modules/shift/entity/ShiftVariance.java
modules/shift/repository/ShiftRepository.java
modules/shift/repository/ShiftHandoverRepository.java
modules/shift/repository/ShiftScheduleRepository.java
modules/shift/repository/ShiftCashUpRepository.java
modules/shift/repository/ShiftVarianceRepository.java
modules/shift/service/ShiftService.java
modules/shift/service/ShiftHandoverService.java
modules/shift/service/ShiftScheduleService.java
modules/shift/service/impl/ShiftServiceImpl.java
modules/shift/service/impl/ShiftHandoverServiceImpl.java
modules/shift/service/impl/ShiftScheduleServiceImpl.java
modules/shift/mapper/ShiftMapper.java
modules/shift/mapper/ShiftHandoverMapper.java
modules/shift/validation/ShiftValidator.java
modules/employee/controller/EmployeeController.java
modules/employee/controller/EmployeeRoleController.java
modules/employee/controller/AttendanceController.java
modules/employee/controller/LeaveController.java
modules/employee/controller/DepartmentController.java
modules/employee/dto/request/CreateEmployeeRequest.java
modules/employee/dto/request/UpdateEmployeeRequest.java
modules/employee/dto/request/CreateAttendanceRequest.java
modules/employee/dto/request/CreateLeaveRequest.java
modules/employee/dto/request/CreateDepartmentRequest.java
modules/employee/dto/response/EmployeeResponse.java
modules/employee/dto/response/EmployeeRoleResponse.java
modules/employee/dto/response/AttendanceResponse.java
modules/employee/dto/response/LeaveResponse.java
modules/employee/dto/response/DepartmentResponse.java
modules/employee/dto/summary/EmployeeSummaryResponse.java
modules/employee/dto/summary/CompleteEmployeeProfileResponse.java
modules/employee/entity/Employee.java
modules/employee/entity/EmployeeRole.java
modules/employee/entity/Department.java
modules/employee/entity/Attendance.java
modules/employee/entity/Leave.java
modules/employee/entity/EmployeePerformance.java
modules/employee/entity/EmploymentContract.java
modules/employee/repository/EmployeeRepository.java
modules/employee/repository/EmployeeRoleRepository.java
modules/employee/repository/DepartmentRepository.java
modules/employee/repository/AttendanceRepository.java
modules/employee/repository/LeaveRepository.java
modules/employee/repository/EmployeePerformanceRepository.java
modules/employee/service/EmployeeService.java
modules/employee/service/EmployeeRoleService.java
modules/employee/service/AttendanceService.java
modules/employee/service/LeaveService.java
modules/employee/service/impl/EmployeeServiceImpl.java
modules/employee/service/impl/EmployeeRoleServiceImpl.java
modules/employee/service/impl/AttendanceServiceImpl.java
modules/employee/service/impl/LeaveServiceImpl.java
modules/employee/mapper/EmployeeMapper.java
modules/employee/mapper/EmployeeRoleMapper.java
modules/employee/mapper/AttendanceMapper.java
modules/employee/validation/EmployeeValidator.java
modules/payroll/controller/PayrollController.java
modules/payroll/controller/PayslipController.java
modules/payroll/dto/request/RunPayrollRequest.java
modules/payroll/dto/request/ApprovePayrollRequest.java
modules/payroll/dto/response/PayrollRunResponse.java
modules/payroll/dto/response/PayslipResponse.java
modules/payroll/dto/summary/PayrollSummaryResponse.java
modules/payroll/entity/PayrollRun.java
modules/payroll/entity/Payslip.java
modules/payroll/entity/PayrollItem.java
modules/payroll/entity/Deduction.java
modules/payroll/entity/Allowance.java
modules/payroll/entity/StatutoryContribution.java
modules/payroll/repository/PayrollRunRepository.java
modules/payroll/repository/PayslipRepository.java
modules/payroll/repository/PayrollItemRepository.java
modules/payroll/repository/StatutoryContributionRepository.java
modules/payroll/service/PayrollService.java
modules/payroll/service/PayslipService.java
modules/payroll/service/impl/PayrollServiceImpl.java
modules/payroll/service/impl/PayslipServiceImpl.java
modules/payroll/mapper/PayrollMapper.java
modules/payroll/validation/PayrollValidator.java
modules/request/controller/RequestController.java
modules/request/controller/ApprovalWorkflowController.java
modules/request/dto/request/CreateRequestRequest.java
modules/request/dto/request/ApproveRequestRequest.java
modules/request/dto/request/RejectRequestRequest.java
modules/request/dto/response/RequestResponse.java
modules/request/dto/response/RequestCommentResponse.java
modules/request/dto/response/ApprovalStepResponse.java
modules/request/dto/summary/RequestSummaryResponse.java
modules/request/entity/Request.java
modules/request/entity/RequestComment.java
modules/request/entity/ApprovalRequest.java
modules/request/entity/ApprovalWorkflow.java
modules/request/entity/ApprovalStep.java
modules/request/repository/RequestRepository.java
modules/request/repository/RequestCommentRepository.java
modules/request/repository/ApprovalRequestRepository.java
modules/request/repository/ApprovalWorkflowRepository.java
modules/request/repository/ApprovalStepRepository.java
modules/request/service/RequestService.java
modules/request/service/ApprovalWorkflowService.java
modules/request/service/impl/RequestServiceImpl.java
modules/request/service/impl/ApprovalWorkflowServiceImpl.java
modules/request/mapper/RequestMapper.java
modules/request/validation/RequestValidator.java
modules/incident/controller/IncidentController.java
modules/incident/dto/request/CreateIncidentRequest.java
modules/incident/dto/request/UpdateIncidentStatusRequest.java
modules/incident/dto/request/EscalateIncidentRequest.java
modules/incident/dto/response/IncidentResponse.java
modules/incident/dto/response/IncidentResolutionResponse.java
modules/incident/dto/response/IncidentAttachmentResponse.java
modules/incident/dto/summary/IncidentSummaryResponse.java
modules/incident/entity/Incident.java
modules/incident/entity/IncidentCategory.java
modules/incident/entity/IncidentResolution.java
modules/incident/entity/IncidentEscalation.java
modules/incident/entity/IncidentAttachment.java
modules/incident/repository/IncidentRepository.java
modules/incident/repository/IncidentCategoryRepository.java
modules/incident/repository/IncidentResolutionRepository.java
modules/incident/repository/IncidentEscalationRepository.java
modules/incident/repository/IncidentAttachmentRepository.java
modules/incident/service/IncidentService.java
modules/incident/service/impl/IncidentServiceImpl.java
modules/incident/mapper/IncidentMapper.java
modules/incident/validation/IncidentValidator.java
modules/facility/controller/FacilityController.java
modules/facility/controller/AssetController.java
modules/facility/dto/request/CreateFacilityRequest.java
modules/facility/dto/request/CreateAssetRequest.java
modules/facility/dto/response/FacilityResponse.java
modules/facility/dto/response/AssetResponse.java
modules/facility/dto/summary/FacilitySummaryResponse.java
modules/facility/entity/Facility.java
modules/facility/entity/Asset.java
modules/facility/entity/ServiceBay.java
modules/facility/entity/CarWashBay.java
modules/facility/entity/GasRefillPoint.java
modules/facility/entity/RetailShop.java
modules/facility/repository/FacilityRepository.java
modules/facility/repository/AssetRepository.java
modules/facility/repository/ServiceBayRepository.java
modules/facility/repository/CarWashBayRepository.java
modules/facility/repository/GasRefillPointRepository.java
modules/facility/service/FacilityService.java
modules/facility/service/AssetService.java
modules/facility/service/impl/FacilityServiceImpl.java
modules/facility/service/impl/AssetServiceImpl.java
modules/facility/mapper/FacilityMapper.java
modules/facility/validation/FacilityValidator.java
modules/finance/controller/ExpenseController.java
modules/finance/controller/PaymentController.java
modules/finance/controller/InvoiceController.java
modules/finance/controller/ReconciliationController.java
modules/finance/dto/request/CreateExpenseRequest.java
modules/finance/dto/request/CreatePaymentRequest.java
modules/finance/dto/request/CreateInvoiceRequest.java
modules/finance/dto/request/RunReconciliationRequest.java
modules/finance/dto/response/ExpenseResponse.java
modules/finance/dto/response/PaymentResponse.java
modules/finance/dto/response/InvoiceResponse.java
modules/finance/dto/response/ReconciliationResponse.java
modules/finance/dto/summary/FinanceSummaryResponse.java
modules/finance/entity/Expense.java
modules/finance/entity/ExpenseCategory.java
modules/finance/entity/Payment.java
modules/finance/entity/Invoice.java
modules/finance/entity/Reconciliation.java
modules/finance/entity/LedgerEntry.java
modules/finance/entity/CashMovement.java
modules/finance/repository/ExpenseRepository.java
modules/finance/repository/ExpenseCategoryRepository.java
modules/finance/repository/PaymentRepository.java
modules/finance/repository/InvoiceRepository.java
modules/finance/repository/ReconciliationRepository.java
modules/finance/repository/LedgerEntryRepository.java
modules/finance/service/ExpenseService.java
modules/finance/service/PaymentService.java
modules/finance/service/InvoiceService.java
modules/finance/service/ReconciliationService.java
modules/finance/service/impl/ExpenseServiceImpl.java
modules/finance/service/impl/PaymentServiceImpl.java
modules/finance/service/impl/InvoiceServiceImpl.java
modules/finance/service/impl/ReconciliationServiceImpl.java
modules/finance/mapper/ExpenseMapper.java
modules/finance/mapper/PaymentMapper.java
modules/finance/mapper/InvoiceMapper.java
modules/finance/validation/FinanceValidator.java
modules/procurement/controller/PurchaseOrderController.java
modules/procurement/controller/GoodsReceiptController.java
modules/procurement/dto/request/CreatePurchaseOrderRequest.java
modules/procurement/dto/request/ReceiveGoodsRequest.java
modules/procurement/dto/response/PurchaseOrderResponse.java
modules/procurement/dto/response/GoodsReceiptResponse.java
modules/procurement/dto/summary/ProcurementSummaryResponse.java
modules/procurement/entity/PurchaseOrder.java
modules/procurement/entity/PurchaseOrderLineItem.java
modules/procurement/entity/GoodsReceipt.java
modules/procurement/entity/SupplierContract.java
modules/procurement/repository/PurchaseOrderRepository.java
modules/procurement/repository/PurchaseOrderLineItemRepository.java
modules/procurement/repository/GoodsReceiptRepository.java
modules/procurement/repository/SupplierContractRepository.java
modules/procurement/service/PurchaseOrderService.java
modules/procurement/service/GoodsReceiptService.java
modules/procurement/service/impl/PurchaseOrderServiceImpl.java
modules/procurement/service/impl/GoodsReceiptServiceImpl.java
modules/procurement/mapper/ProcurementMapper.java
modules/procurement/validation/ProcurementValidator.java
modules/maintenance/controller/WorkOrderController.java
modules/maintenance/controller/MaintenanceScheduleController.java
modules/maintenance/dto/request/CreateWorkOrderRequest.java
modules/maintenance/dto/request/CreateMaintenanceScheduleRequest.java
modules/maintenance/dto/response/WorkOrderResponse.java
modules/maintenance/dto/response/MaintenanceScheduleResponse.java
modules/maintenance/dto/summary/MaintenanceSummaryResponse.java
modules/maintenance/entity/WorkOrder.java
modules/maintenance/entity/MaintenanceSchedule.java
modules/maintenance/entity/ServiceTask.java
modules/maintenance/entity/SparePartUsage.java
modules/maintenance/repository/WorkOrderRepository.java
modules/maintenance/repository/MaintenanceScheduleRepository.java
modules/maintenance/repository/ServiceTaskRepository.java
modules/maintenance/repository/SparePartUsageRepository.java
modules/maintenance/service/WorkOrderService.java
modules/maintenance/service/MaintenanceScheduleService.java
modules/maintenance/service/impl/WorkOrderServiceImpl.java
modules/maintenance/service/impl/MaintenanceScheduleServiceImpl.java
modules/maintenance/mapper/WorkOrderMapper.java
modules/maintenance/validation/MaintenanceValidator.java
modules/compliance/controller/ComplianceAuditController.java
modules/compliance/controller/SafetyInspectionController.java
modules/compliance/controller/DocumentRegistryController.java
modules/compliance/dto/request/CreateComplianceAuditRequest.java
modules/compliance/dto/request/CreateSafetyInspectionRequest.java
modules/compliance/dto/request/RegisterDocumentRequest.java
modules/compliance/dto/response/ComplianceAuditResponse.java
modules/compliance/dto/response/SafetyInspectionResponse.java
modules/compliance/dto/response/DocumentRegistryResponse.java
modules/compliance/dto/summary/ComplianceSummaryResponse.java
modules/compliance/entity/ComplianceAudit.java
modules/compliance/entity/ComplianceCheckpoint.java
modules/compliance/entity/SafetyInspection.java
modules/compliance/entity/DocumentRegistry.java
modules/compliance/repository/ComplianceAuditRepository.java
modules/compliance/repository/ComplianceCheckpointRepository.java
modules/compliance/repository/SafetyInspectionRepository.java
modules/compliance/repository/DocumentRegistryRepository.java
modules/compliance/service/ComplianceAuditService.java
modules/compliance/service/SafetyInspectionService.java
modules/compliance/service/impl/ComplianceAuditServiceImpl.java
modules/compliance/service/impl/SafetyInspectionServiceImpl.java
modules/compliance/mapper/ComplianceMapper.java
modules/compliance/validation/ComplianceValidator.java
modules/reporting/controller/ReportingController.java
modules/reporting/controller/SalesReportController.java
modules/reporting/controller/InventoryReportController.java
modules/reporting/controller/FinanceReportController.java
modules/reporting/dto/request/ReportFilterRequest.java
modules/reporting/dto/response/SalesReportResponse.java
modules/reporting/dto/response/InventoryReportResponse.java
modules/reporting/dto/response/FinanceReportResponse.java
modules/reporting/dto/response/BranchPerformanceResponse.java
modules/reporting/dto/projection/DailySalesProjection.java
modules/reporting/dto/projection/StockVarianceProjection.java
modules/reporting/dto/projection/BranchPerformanceProjection.java
modules/reporting/service/ReportingService.java
modules/reporting/service/SalesReportService.java
modules/reporting/service/InventoryReportService.java
modules/reporting/service/FinanceReportService.java
modules/reporting/service/impl/ReportingServiceImpl.java
modules/reporting/service/impl/SalesReportServiceImpl.java
modules/reporting/service/impl/InventoryReportServiceImpl.java
modules/reporting/service/impl/FinanceReportServiceImpl.java
modules/reporting/query/SalesAnalyticsQueryRepository.java
modules/reporting/query/InventoryAnalyticsQueryRepository.java
modules/reporting/query/BranchPerformanceQueryRepository.java
modules/reporting/export/CsvExportService.java
modules/reporting/export/PdfExportService.java
modules/reporting/export/ExcelExportService.java
modules/sync/controller/SyncController.java
modules/sync/dto/request/SyncRequest.java
modules/sync/dto/request/SyncBatchRequest.java
modules/sync/dto/request/ResolveSyncConflictRequest.java
modules/sync/dto/response/SyncResponse.java
modules/sync/dto/response/SyncConflictResponse.java
modules/sync/dto/response/SyncCheckpointResponse.java
modules/sync/dto/summary/SyncSummaryResponse.java
modules/sync/entity/SyncChange.java
modules/sync/entity/SyncBatch.java
modules/sync/entity/SyncConflict.java
modules/sync/entity/SyncCheckpoint.java
modules/sync/entity/DeviceRegistration.java
modules/sync/repository/SyncChangeRepository.java
modules/sync/repository/SyncBatchRepository.java
modules/sync/repository/SyncConflictRepository.java
modules/sync/repository/SyncCheckpointRepository.java
modules/sync/repository/DeviceRegistrationRepository.java
modules/sync/service/SyncService.java
modules/sync/service/SyncConflictService.java
modules/sync/service/impl/SyncServiceImpl.java
modules/sync/service/impl/SyncConflictServiceImpl.java
modules/sync/mapper/SyncMapper.java
modules/sync/validation/SyncValidator.java
jobs/reporting/DailySalesAggregationJob.java
jobs/reporting/MonthlyBranchPerformanceJob.java
jobs/reporting/ScheduledReportDispatchJob.java
jobs/alerts/LowStockAlertJob.java
jobs/alerts/IncidentEscalationJob.java
jobs/alerts/SubscriptionExpiryAlertJob.java
jobs/alerts/ShiftOverdueAlertJob.java
jobs/sync/SyncRetryJob.java
jobs/sync/SyncCleanupJob.java
jobs/sync/SyncConflictReminderJob.java
jobs/maintenance/MaintenanceReminderJob.java
jobs/maintenance/PumpCalibrationReminderJob.java
jobs/maintenance/ComplianceExpiryReminderJob.java
EOF
)

create_java_file() {
  local rel="$1"
  local full="$BASE_DIR/$rel"
  local dir pkg file class_name type

  dir="$(dirname "$full")"
  file="$(basename "$full")"
  mkdir -p "$dir"

  if [[ -f "$full" ]]; then
    echo "SKIP  $rel"
    return
  fi

  pkg="${rel%/*}"
  if [[ "$pkg" == "$rel" ]]; then
    pkg="com.angerasilas.petroflow_backend"
  else
    pkg="com.angerasilas.petroflow_backend.${pkg//\//.}"
  fi

  class_name="${file%.java}"

  type="class"
  if [[ "$class_name" == *Repository || "$class_name" == *Service || "$class_name" == *Mapper || "$class_name" == *Client || "$class_name" == *Provider || "$class_name" == *Handler || "$class_name" == *Validator ]]; then
    type="interface"
  fi
  if [[ "$class_name" == Valid* ]]; then
    type="annotation"
  fi
  if [[ "$pkg" == *".common.enums" ]]; then
    type="enum"
  fi

  {
    echo "package $pkg;"
    echo

    case "$type" in
      enum)
        echo "public enum $class_name {"
        echo "    PLACEHOLDER"
        echo "}"
        ;;
      annotation)
        echo "public @interface $class_name {"
        echo "}"
        ;;
      interface)
        echo "public interface $class_name {"
        echo "}"
        ;;
      *)
        if [[ "$class_name" == "PetroflowBackendApplication" ]]; then
          echo "public class $class_name {"
          echo "    public static void main(String[] args) {"
          echo "    }"
          echo "}"
        else
          echo "public class $class_name {"
          echo "}"
        fi
        ;;
    esac
  } > "$full"

  echo "CREATE $rel"
}

while IFS= read -r rel; do
  [[ -z "$rel" ]] && continue
  create_java_file "$rel"
done <<< "$FILES"

echo
echo "Done. Target tree created under: $BASE_DIR"